name: Test and build

on:
  push:
    branches-ignore:
      - master

env:
  CI: true
jobs:
  test-and-build:
    name: Test and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.13.1'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn
      - name: Test
        run: yarn test --coverage
      - name: Build
        run: yarn build
